### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by schoettl**
Hi @ldreier, thank you very much for your effort porting this add-on to new Thunderbird!

Since there is still no other alternative, I'd like to make this add-on publicly available again.

Do you still want to maintain this repo, merge PRs, update the Thunderbird add-on store, …?

If yes, I'd like provide this PR. And one of us could submit it to the add-on store.

If you don't have much time to continue maintenance, I'd maintain a fork under my username and publish it to the add-on store. Mentioning you and the original author, of course.

### CODE REVIEW

**Comment by ldreier** [comment]
Hallo @schoettl,
my original understanding approx. one year ago in the discussion about my (still open) pull request was that @dennisverspuij would adopt the code if ready and update the official add-on. From my side the code is stable for approx. one year, but Dennis stayed silent.
Maybe we give him also the opportunity to comment.

Regarding your proposal I have not yet a final opinion. I have only limited capacity for maintenance, but I am not sure how much effort would be required. Javascript is also not the programming language I use in daily work, so I always need some time to "switch" to this language.

**Comment by ldreier** [comment]
Hallo @schoettl,

after some thinking, I "volunteer" to publish this branch on the Thunderbird add-on store. This is new for me, but I like to give it a try... I had a look in the release procedure...
If maintenance becomes to much of work ... I come back to you ...
Lets see if there are requirements to do more changes to publish it (e.g. add-on naming, guid etc.).

Cheers und Frohe Weihnachten

**Comment by schoettl** [comment]
Hey, thanks for merging and taking care of this add-on!! It will be a nice Christmas present for many users, I think ;-)

Could you post the link to the add-on store here when you're done? I'm looking forward to install from the store and at my colleagues' computers.

I could also provide a PR to put the link to the add-on store in the README.

**Comment by schoettl** [comment]
PS: I think it would be good to
```
git tag 2.0.0
```
like in [semantic versioning](https://semver.org/). Then `make_xpi.sh` would yield a nice .xpi package name.

Eine schöne Weihnachtszeit as well!

**Comment by ldreier** [comment]
@schoettl 

Today I was trying to submit the add-on for publication on the Thunderbird add-on store. As expected I need to change the GUID of the add-on. This may effect the transfer of existing configuration settings of the old add-on to the new one.

A more severe issue was the use of "experimental APIs". The submission filters require to define a "strict_max_version" in manifest.json for add-ons which use experimental APIs. And unfortunately the version entry must be an existing version.
So I submitted the add-on with:
"strict_max_version": "91.*"
I think that would mean that acc. https://wiki.mozilla.org/Release_Management/Calendar ("Thunderbird tracks the ESR schedule column...") we would need updates 2 or 3 times per year just to track the latest version.

An alternative would be to push for inclusion of the required features into the standard add-on API.

The add-on was submitted as "correct identity 2", but is waiting for approval.

Lets see...

**Comment by schoettl** [comment]
OK, changing the max version two times a year should be manageable. Did the submission filter also tell you which API is experimental?

**Comment by dennisverspuij** [comment]
@ldreier a.o. I noticed the vigorous activity regarding new release, many thanks for the work! And sorry that I didn't take promised time anymore to investigate the issues I encountered further, Please go ahead releasing the v2, though a bit late in this process, my offer still stands for giving you collab access, or transfer the repo? Likewise I can add you as owner for the addon listing, making it easier to release and allow users to upgrade retaining settings. If so let me know how I can reach you, I need an email adress for that. Greetings Dennis

**Comment by ldreier** [comment]
> Did the submission filter also tell you which API is experimental?

Not directly, but the ["WebExtension Experiments" API](https://webextension-api.thunderbird.net/en/91/how-to/experiments.html)
is a method to extend the functionality currently not available for a WebExtension.
For this add-on the interface is defined in schema.json and implemented in scripts/exp_api.js.

**Comment by schoettl** [comment]
Hi @ldreier, how is the submission process going?

**Comment by ldreier** [comment]
Still status "Wartet auf Überprüfung" (Waiting for review).

Was submitted on Dec. 22th. I saw later some message on the add-on submission page "may take 3...4 weeks due to large number of submissions"

**Comment by schoettl** [comment]
Wow, that's long. OK.

**Comment by ldreier** [comment]
Version is 2.0.1 is now available:
https://addons.thunderbird.net/de/thunderbird/addon/correct-identity/

**Comment by schoettl** [comment]
Nice, thanks for your efforts! What's the upstream GitHub repo for PRs, now? @ldreier or @dennisverspuij ?

**Comment by ldreier** [comment]
I would consider @dennisverspuij as the the main repository.
I was even thinking of deleting this branch here?

**Comment by schoettl** [comment]
Ah allright, I didn't notice that he merged this fork. I guess your fork repo don't hurt, but I don't mind ;)

**Pull request merged**
